CREATE DATABASE IF NOT EXISTS cyclopedia;
use cyclopedia;
CREATE TABLE IF NOT EXISTS USER_INFO
(
	USER_ID INT AUTO_INCREMENT PRIMARY KEY,
	F_NAME CHAR(50) NOT NULL,
	L_NAME CHAR(50) NOT NULL,
	EMAIL CHAR(100) NOT NULL,
	CREATION_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS JOURNEY
(
	JOURNEY_ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT NOT NULL,
	LATITUDE FLOAT NOT NULL,
	LONGITUDE FLOAT NOT NULL,
	TIMESTAMP INT NOT NULL,
	ALTITUDE INT NOT NULL,
	JOURNEY_START_TIME INT NOT NULL,
	JOURNEY_END_TIME INT NOT NULL,
	FOREIGN KEY (USER_ID)
	REFERENCES USER_INFO(USER_ID)
);
CREATE TABLE IF NOT EXISTS POINT_OF_INTEREST_TYPE
(
      POI_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY,
      POI_TYPE_NAME CHAR(50) NOT NULL,
      POI_TYPE_DESCRIPTION VARCHAR(256)
);
CREATE TABLE IF NOT EXISTS POINT_OF_INTEREST
(
      POI_ID INT AUTO_INCREMENT PRIMARY KEY,
      POI_TYPE_ID INT NOT NULL,
      LATITUDE FLOAT NOT NULL,
        LONGITUDE FLOAT NOT NULL,
        TIMESTAMP INT NOT NULL,
      ALTITUDE INT NOT NULL,
      COMMENTS VARCHAR(1000),
      FOREIGN KEY (POI_TYPE_ID)
      REFERENCES POINT_OF_INTEREST_TYPE(POI_TYPE_ID)
);


CREATE TABLE IF NOT EXISTS TRACK_NAME
(
	TRACK_ID INT AUTO_INCREMENT PRIMARY KEY,
	TRACK_NAME CHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRACK_DATA
(
	POINT_ID INT AUTO_INCREMENT PRIMARY KEY,
	TRACK_ID INT NOT NULL,
	LATITUDE FLOAT NOT NULL,
        LONGITUDE FLOAT NOT NULL,
        TIMESTAMP INT NOT NULL,
        ALTITUDE INT NOT NULL,
	FOREIGN KEY (TRACK_ID)
	REFERENCES TRACK_NAME(TRACK_ID)

)
;

CREATE TABLE IF NOT EXISTS TRACK_RATING
(
	RATING_ID INT AUTO_INCREMENT PRIMARY KEY,
	TRACK_ID INT NOT NULL,
	USER_ID INT NOT NULL,
	RATING INT NOT NULL,
	COMMENTS VARCHAR(1000),
	FOREIGN KEY (TRACK_ID)
        REFERENCES TRACK_NAME(TRACK_ID),
	FOREIGN KEY (USER_ID)
        REFERENCES USER_INFO(USER_ID)

);







